engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true

tools:
  eslint:
    config: eslint.config.mjs
    patterns:
      include_paths:
        - source/
        - specs/
      exclude_paths:
        - admin/
        - .github/
        - "**/*.md"

  stylelint:
    patterns:
      include_paths:
        - source/
        - specs/
      exclude_paths:
        - admin/
        - .github/
        - "**/*.md"

coverage:
  enabled: false

notifications:
  github:
    annotations: false
  slack: false
